name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚨 Breaking Changes"
    labels:
      - "breaking-change"
  - title: "🚀 Features & Changes"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "📚 Documentation"
    labels:
      - "documentation"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
exclude-labels:
  - "invalid"
  - "wontfix"
  - "dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-template: "$MAJOR.$MINOR.$PATCH"
version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
  minor:
    labels:
      - "minor"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "bug"
      - "bugfix"
      - "chore"
      - "dependencies"
      - "documentation"
      - "fix"
      - "schema"
      - "hotfix"
  default: minor
prerelease: false
commitish: master
filter-by-commitsh: true
template: |
  ## What’s Changed

  $CHANGES
