name: Release Drafter

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      nextVersion:
        description: 'Version to be drafted'     
        required: true
  
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yaml
          name: ${{ github.event.inputs.nextVersion }}
          tag: ${{ github.event.inputs.nextVersion }}
          version: ${{ github.event.inputs.nextVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
