name: Pre-Release Drafter

# yamllint disable-line rule:truthy
on:
#  push:
#    branches:
#      - dev
  workflow_dispatch:
    inputs:
      nextVersion:
        description: 'Version to be drafted'     
        required: true

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-prerelease.yaml
          name: ${{ github.event.inputs.nextVersion }}
          tag: ${{ github.event.inputs.nextVersion }}
          version: ${{ github.event.inputs.nextVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - uses: octokit/request-action@v2.x
#        id: get_latest_release
#        with:
#          route: GET /repos/{owner}/{repo}/releases
#          owner: roflcoopter
#          repo: release-drafter-test
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - uses: actions/setup-python@v2
#      - uses: actions/checkout@v2
#      - id: release_data
#        name: create response.json
#        run: |
#          echo '${{ steps.get_latest_release.outputs.data }}' > response.json
          
#          python3 ./.github/workflows/calculate_beta_release.py

#      - uses: octokit/request-action@v2.x
#        id: update_check_run
#        with:
#          route: PATCH /repos/{owner}/{repo}/releases/{release_id}
#          owner: roflcoopter
#          repo: release-drafter-test
#          release_id: ${{ env.VISERON_RELEASE_ID }}
#          tag_name: ${{ env.VISERON_TAG_NAME }}
#          name: ${{ env.VISERON_TAG_NAME }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
