name: Test workflow

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - id: release_drafter
        run: echo "::set-output name=id::1.0.1"

      - uses: octokit/request-action@v2.0.2
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases
          owner: roflcoopter
          repo: release-drafter-test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - run: "echo ${{ steps.release_drafter.outputs.id }}"
      - run: "echo ${{ steps.get_latest_release.data }}"
      - run: "echo ${{ fromJson(steps.get_latest_release.outputs.data)[0] }}"
     
      - name: create response.json
        run: echo '${{ steps.get_latest_release.outputs.data }}' > response.json
      - name: read response.json
        run: cat response.json
      
#      - uses: actions/checkout@v2
#      - uses: actions/setup-python@v2
#        with:
#          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
#      - run: echo ${{ steps.get_latest_release.outputs.data }} | python -c "import sys, json; print(json.load(sys.stdin)[0])"
