name: Test workflow

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      #- id: release_drafter
      #  run: echo "::set-output name=id::1.0.1"

      - uses: octokit/request-action@v2.0.2
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases
          owner: roflcoopter
          repo: release-drafter-test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      #- run: "echo ${{ steps.release_drafter.outputs.id }}"
      #- run: "echo ${{ steps.get_latest_release.data }}"
      #- run: "echo ${{ fromJson(steps.get_latest_release.outputs.data)[0] }}"

      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2
      - id: release_data
        name: create response.json
        run: |
          echo '${{ steps.get_latest_release.outputs.data }}' > response.json
          
          python3 ./.github/workflows/calculate_beta_release.py
      #- run: |
      #    echo ${{ steps.release_data.outputs.release_id }}
      #- run: "echo ${{ steps.release_data.outputs.release_id }}"
      - run: |
          echo ${{ env.release_id }}
      - name: "Show environment variables"
        run: |
          env

      - uses: octokit/request-action@v2.x
        id: update_check_run
        with:
          route: PATCH /repos/{owner}/{repo}/releases/{release_id}
          owner: roflcoopter
          repo: release-drafter-test
          release_id: ${{ env.VISERON_RELEASE_ID }}
          tag_name: ${{ env.VISERON_TAG_NAME }}
          name: ${{ env.VISERON_TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
